### ISSUE TITLE
Prepare the project for submission 

### ISSUE THREAD

**Issue by simo1427** [simo1427/quantum-minor-proj#1]
## TODO

- [x] Update `requirements.txt` to include also the dependencies of `quantuminspire` and `qiskit`
- [x] Update README.md
- [ ] Push the report's source code?

The list is subject to change as the project progresses, this is all preliminary items
