### ISSUE TITLE
Prepare images for processing

### ISSUE THREAD

**Issue by simo1427** [simo1427/quantum-minor-proj#2]
The goal is to make a method which takes in an RGB image, and outputs three grayscale images - a luminance image and two chrominance channels. The latter are subsampled with the goal of reducing the number of qubits needed for their rendition.

## TODO
- [x] Add OpenCV as a dependency
- [x] Convert images to YCbCr (or another color space) for chroma subsampling
- [x] Subsample the chrominance channels
- [x] Make a method for reconstructing the images
